// Actions
export const SESSION_INIT = 'SESSION_INIT';
export const SESSION_SET_POSITION = 'SESSION_SET_POSITION';

// Mutations
export const SESSION_SET_STATE_PROPERTY = 'SESSION_SET_STATE_PROPERTY';
